version: 2.3.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Leaderboards
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

init:
  - git config --global core.autocrlf false

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: toofz.sln
  verbosity: minimal

deploy_script:
  - ps: .\Deploy-NuGetPackage.ps1