version: 2.4.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz
  COVERALLS_REPO_TOKEN:
    secure: yOO1uv2WMuoBci3X+xcjGeYZ0vt5CS8QwLFr9o4On60cc5t6RG+tjaDMUy13OqPP
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

init:
  - git config --global core.autocrlf false

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: toofz.sln
  verbosity: minimal

test_script:
  - ps: .\Test-Project.ps1 -Assembly $env:PROJECT
after_test:
  - ps: .\Submit-CodeCoverageResults.ps1

deploy_script:
  - ps: .\Deploy-NuGetPackage.ps1