coverage:
  notify:
    slack:
      default:
        url: secret:JDweHgA1Iz2HUb08Fb0Ey9NkO0GX//UIaRCrGeXHklCNSNauycKkW+e4HDnqiouYrg8/p90I5vgpWCPyi5+loQlX8/eZEJYlr3kXHYWXBTjiZKk/mtoF5xIos2FVGkbMb32CdOWOeeZ4u2S+SZV5ThCVZ072xEfKQL+Rr3+pM+g=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null